artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Divyanshu9822/ml-ops-holiday-package-prediction/raw/main/data/raw/travel.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  raw_data_path: artifacts/data_ingestion/travel.csv
  processed_data_path: artifacts/data_validation/travel_processed.csv
  STATUS_FILE: artifacts/data_validation/status.txt
